CONDITIONAL AND CONTROL FLOW.
EQUIALITY
```{r}
"Test" != "test" # case sensitive
TRUE == FALSE
-6*15!=17-101
TRUE == 1
# GREATER THAN
-5*5+2>=-10+1

"raining" <= "raining dos"

TRUE < FALSE # 1 < 0
```
compare vectors
```{r}
linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,9,13,5,2,13,14)
linkedin > 13
facebook <= 5
linkedin > facebook

```
COMPARE MATRICES
```{r}
views <- matrix(c(linkedin, facebook), nrow = 2, byrow = TRUE)
views
views==13
views<=14
```
& |
```{r}
linkedin
last <- tail(linkedin,1)

last <5 | last > 10
last <5 & last > 20

linkedin >10 & facebook < 10 #compare each element
linkedin >=12 | facebook >= 12

```
CONDITIONAL STATEMENTS
```{r}
MEDIUUM <- "linkedin"
num_views <- 14
if (MEDIUUM == "linkedin"){
  print("shows linkedin info")
} else if (MEDIUUM == "facebook"){
  print("shows linkedin info")
} else {
  print("unknow")
}
if (num_views > 13){
  print("you are popular")
  

}
```

your number of views
```{r}
#if anidados
```

loops
```{r}
#  while (condition){exp}
speed<- 70
while (speed > 30){
  print("slow down")
  speed <- speed -7
  #you can use conditions
  #to stop the loop, use break
  
}
```
Loop over a vector
```{r}
linkedin <- c(86,9,13,5,2,17,14)
for (l in linkedin){
  
  print(l)
}

for (i in 1:length(linkedin)){
  print(linkedin[i])
}
```
loop over a list

```{r}
# nyc<- lisst (pop =8405837, barauhg=c('city1', 'city','city3) )
```

loop over a matrix
```{r}
new_hope <- c(460.998,314.4)
empirte_strikes <- c(290.475,247.900)
return_jedi <- c(309.306,165.8)

box_office <- c(new_hope,empirte_strikes,return_jedi)
box_office

star_wars_matrix <- matrix(box_office, byrow = TRUE, nrow = 3)
star_wars_matrix
colnames(star_wars_matrix) <-c("US","non-US")
rownames(star_wars_matrix) <-c("new_hope","empirte_strikes","return_jedi")
star_wars_matrix
rowSums(star_wars_matrix)

for (i in 1:nrow(star_wars_matrix)){
  for (j in 1:ncol(star_wars_matrix)){
  print(star_wars_matrix[i][j])
}
}
```


```{r}
# you cna add condition inside loops
linkedin <- c(86,9,13,5,2,17,14)
for (l in linkedin){
  
  if(l >10){
    print("you are popular")
  }
  else{
    break
  }
}
```





